In [1]:
%load_ext nb_black
%load_ext autoreload
%autoreload 2

<IPython.core.display.Javascript object>

In [2]:
import json
import os
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics.cluster import normalized_mutual_info_score
from mstream.mstream import Mstream

<IPython.core.display.Javascript object>

In [3]:
DS_DIR = "data"
DS_NAMES = ["News", "News-T", "Tweets", "Tweets-T"]
DS_PATHS = [os.path.join(DS_DIR, ds_name) for ds_name in DS_NAMES]

<IPython.core.display.Javascript object>

In [40]:
def load_batches(ds_path, batch_size=int(2 ** 8)):
    with open(ds_path) as f:
        docs = []
        for line in f:
            parsed_line = json.loads(line)
            doc = {}
            doc["id"] = parsed_line["Id"]
            doc["word_list"] = parsed_line["textCleaned"].split()
            docs.append(doc)
            if len(docs) == batch_size:
                yield docs
                docs = []
        if len(docs) > 0:
            yield docs

<IPython.core.display.Javascript object>

In [46]:
mstream = Mstream()
for batch in load_batches(DS_PATHS[0]):
    res = mstream.process(batch)

[4.47024055e-07 6.30141993e-13] [0 1]
[9.99998590e-01 1.40963579e-06] [0 1]
[1.73259310e-13 1.87362707e-23] [0 2]
[1.00000000e+00 1.08140051e-10] [0 2]
[1.51566871e-17 8.14485261e-30] [0 3]
[1.00000000e+00 5.37376839e-13] [0 3]
[5.30157686e-11 2.00908238e-17] [0 4]
[9.99999621e-01 3.78959256e-07] [0 4]
[1.49241501e-18 6.83644255e-30] [0 5]
[1.00000000e+00 4.58079188e-12] [0 5]
[2.81598601e-15 1.15021893e-23] [0 6]
[9.99999996e-01 4.08460455e-09] [0 6]
[1.02062077e-11 1.76643958e-17] [0 7]
[9.99998269e-01 1.73074718e-06] [0 7]
[5.55587445e-08 2.45024273e-11] [0 8]
[9.99559176e-01 4.40823965e-04] [0 8]
[8.71855149e-22 4.49753678e-33] [0 9]
[1.00000000e+00 5.15858258e-12] [0 9]
[3.53612226e-12 1.68503684e-17] [ 0 10]
[9.99995235e-01 4.76518820e-06] [ 0 10]
[2.21821943e-18 8.09463697e-27] [ 0 11]
[9.99999996e-01 3.64915969e-09] [ 0 11]
[2.11144242e-10 1.99692885e-14] [ 0 12]
[9.99905432e-01 9.45675804e-05] [ 0 12]
[1.31371861e-14 1.32635406e-20] [ 0 13]
[9.99998990e-01 1.00961706e-06] [ 0 

[5.70044840e-03 9.93590953e-01 7.08599030e-04] [  0 109 137]
[1.69676451e-19 9.67541004e-17 1.23599410e-20] [  0 109 138]
[1.75039419e-03 9.98122100e-01 1.27506020e-04] [  0 109 138]
[1.68447171e-19 8.32189510e-17 1.23593110e-20] [  0 109 139]
[2.01975612e-03 9.97832050e-01 1.48193609e-04] [  0 109 139]
[1.67235575e-19 7.18656840e-17 1.23586901e-20] [  0 109 140]
[2.32125656e-03 9.97507203e-01 1.71540598e-04] [  0 109 140]
[8.62408174e-14 2.97941254e-12 1.84809029e-14] [  0 109 141]
[0.02796273 0.96604502 0.00599225] [  0 109 141]
[1.64863929e-19 5.72146563e-17 1.27281989e-20] [  0 109 142]
[2.87258181e-03 9.96905643e-01 2.21775576e-04] [  0 109 142]
[1.18061077e-16 1.14313098e-14 1.53184120e-17] [  0 109 143]
[0.01020875 0.98846666 0.00132458] [  0 109 143]
[7.72813098e-21 1.90347276e-19 9.70643617e-24] [  0 109 144]
[3.90141937e-02 9.60936805e-01 4.90013409e-05] [  0 109 144]
[7.87786644e-15 3.16984752e-13 1.53169678e-17] [  0 109 145]
[2.42486965e-02 9.75704157e-01 4.71468393e-05] [

AttributeError: 'Mstream' object has no attribute '_Mstream__iter__num'

<IPython.core.display.Javascript object>